from enum import Enum, auto


class Components(Enum):
    CONTAINER = auto()
    LOADER = auto()
    DATA_STORE = auto()
    LEAGUE_TAB = auto()
    TEAM_TAB = auto()
    COUNTRY_DROPDOWN = auto()
    LEAGUE_DROPDOWN = auto()
    TEAM_DROPDOWN = auto()
    HALF_RADIO = auto()
    VENUE_RADIO = auto()
    HISTORY_RADIO = auto()
    LEAGUE_TABLE = auto()
    RESULTS_TABLE = auto()
    GOALS_PIE = auto()
    GOALS_GRAPH = auto()
    BTS_GRAPH = auto()
    RESULTS_PIE = auto()
    RESULTS_GRAPH = auto()
    SCORES_HEATMAP = auto()
    TEAM_GOALS_PIE = auto()
    TEAM_GOALS_GRAPH = auto()
    TEAM_SCORES_HEATMAP = auto()
    TEAM_SCORED_AND_CONCEDED_GRAPH = auto()
    TEAM_RESULTS_PIE = auto()
    TEAM_RESULTS_GRAPH = auto()
    TEAM_RESULTS_TABLE = auto()
    TEAM_FIXTURES_TABLE = auto()
    TEAM_NEXT_FIXTURE = auto()
    TEAM_FIXTURES_CARD = auto()
    TEAM_RESULTS_CARD = auto()
