ugly_separator = '-'
pretty_separator = ' '


def prettify(country_name: str) -> str:
    if ugly_separator in country_name:
        lexemes = country_name.split(ugly_separator)
        return pretty_separator.join(lex.capitalize() for lex in lexemes)
    else:
        return country_name


def uglify(country_name: str) -> str:
    if pretty_separator in country_name:
        lexemes = country_name.split(pretty_separator)
        return ugly_separator.join(lex.capitalize() for lex in lexemes)
    else:
        return country_name


class League:
    def __init__(self, country: str, name: str, code: str):
        self.country = country
        self.name = name
        self.code = code

    def __eq__(self, other):
        if type(other) == type(self):
            return self.__dict__ == other.__dict__
        return NotImplemented

    def __hash__(self):
        return self.country.__hash__() + self.name.__hash__()

    def __str__(self):
        return '{} {}'.format(prettify(self.country), self.name)


country_register = [
    'Albania',
    'Algeria',
    'Argentina',
    'Australia',
    'Austria',
    'Azerbaidjan',
    'Bahrain',
    'Bangladesh',
    'Belarus',
    'Belgium',
    'Bolivia',
    'Bosnia',
    'Brazil',
    'Bulgaria',
    'Cambodia',
    'Canada',
    'Chile',
    'China',
    'Colombia',
    'Costa-Rica',
    'Croatia',
    'Cyprus',
    'Czech-Republic',
    'Denmark',
    'Ecuador',
    'Egypt',
    'England',
    'Estonia',
    'Ethiopia',
    'Faroe-Islands',
    'Finland',
    'France',
    'Georgia',
    'Germany',
    'Ghana',
    'Greece',
    'Guatemala',
    'Honduras',
    'Hungary',
    'Iceland',
    'India',
    'Indonesia',
    'Iran',
    'Ireland',
    'Israel',
    'Italy',
    'Jamaica',
    'Japan',
    'Jordan',
    'Kazakhstan',
    'Kenya',
    'Kosovo',
    'Kuwait',
    'Latvia',
    'Liechtenstein',
    'Lithuania',
    'Luxembourg',
    'Macedonia',
    'Malaysia',
    'Malta',
    'Mexico',
    'Moldova',
    'Montenegro',
    'Morocco',
    'Netherlands',
    'New-Zealand',
    'Nicaragua',
    'Nigeria',
    'Northern-Ireland',
    'Norway',
    'Oman',
    'Panama',
    'Paraguay',
    'Peru',
    'Poland',
    'Portugal',
    'Qatar',
    'Romania',
    'Russia',
    'Saudi-Arabia',
    'Scotland',
    'Serbia',
    'Singapore',
    'Slovakia',
    'Slovenia',
    'South-Africa',
    'South-Korea',
    'Spain',
    'Sweden',
    'Switzerland',
    'Syria',
    'Tanzania',
    'Thailand',
    'Tunisia',
    'Turkey',
    'Ukraine',
    'United-Arab-Emirates',
    'Uruguay',
    'USA',
    'Uganda',
    'Uzbekistan',
    'Venezuela',
    'Vietnam',
    'Wales']

leagues = [League('Algeria', 'Ligue 1', 'ALG1'),
           League('Algeria', 'U21 League 1', 'ALG1U'),
           League('Argentina', 'Liga Profesional Argentina', 'ARG1'),
           League('Argentina', 'Primera Nacional', 'ARG2A'),
           League('Argentina', 'Primera B Metropolitana', 'ARG2B'),
           League('Argentina', 'Primera C', 'ARG3'),
           League('Australia', 'A-League', 'AUS1'),
           League('Australia', 'W-League', 'AUS1W'),
           League('Austria', 'Bundesliga', 'AUT1'),
           League('Austria', '2. Liga', 'AUT2'),
           League('Azerbaidjan', 'Premyer Liqa', 'AZE1'),
           League('Belgium', 'Jupiler Pro League', 'BEL1'),
	   #League('Bangladesh', 'Premier League', 'BGD1'),
           League('Brazil', 'Serie A', 'BRA1'),
           League('Brazil', 'Serie B', 'BRA2'),
           League('Brazil', 'Serie C', 'BRA3'),
           League('Brazil', 'Brasileiro Women', 'BRA1W'),
           League('Bulgaria', 'First League', 'BGR1'),
           League('Bolivia', 'Primera División', 'BOL1'),
           League('Bosnia', 'Premijer Liga', 'BIH1'),
	   #League('Cambodia', 'C-League', 'CAM1'),
           League('Switzerland', 'Super League', 'CHE1'),
           League('Switzerland', 'Challenge League', 'CHE2'),
           League('Switzerland', 'Nationalliga A Women', 'CHE1W'),
           League('China', 'Super League', 'CHN1'),
           League('China', 'League One', 'CHN2'),
           League('Chile', 'Primera División', 'CHL1'),
           League('Chile', 'Primera B', 'CHL2'),
           League('Colombia', 'Primera A', 'COL1'),
           League('Colombia', 'Primera B', 'COL2'),
           League('Costa-Rica', 'Primera División', 'CRI1'),
           League('Costa-Rica', 'Liga de Ascenso', 'CRI2'),
           League('Croatia', 'HNL', 'HRV1'),
           League('Croatia', 'First NL', 'HRV2'),
           League('Czech-Republic', 'Czech Liga', 'CZE1'),
           League('Czech-Republic', 'FNL', 'CZE2'),
           League('Czech-Republic', '3. liga - CFL A', 'CZE3A'),
           League('Czech-Republic', '3. liga - CFL B', 'CZE3B'),
           League('Czech-Republic', '3. liga - MSFL', 'CZE3C'),
           League('Czech-Republic', '1. Liga U19', 'CZE1U'),
           League('Czech-Republic', '1. Liga Women', 'CZE1W'),
           League('Germany', 'Bundesliga', 'DE1'),
           League('Germany', '2. Bundesliga', 'DE2'),
           League('Germany', '3. Liga', 'DE3'),
           League('Germany', 'Regionalliga - Nord', 'DE4A'),
           League('Germany', 'Regionalliga - Nordost', 'DE4B'),
           League('Germany', 'Regionalliga - SudWest', 'DE4C'),
           League('Germany', 'Regionalliga - West', 'DE4D'),
           League('Germany', 'Regionalliga - Bayern', 'DE4E'),
           League('Germany', 'U19 Bundesliga', 'DE1U'),
           League('Germany', 'Frauen Bundesliga', 'DE1W'),
           League('Denmark', 'Superliga', 'DNK1'),
           League('Denmark', '1. Division', 'DNK2'),
           League('Denmark', '2nd Division - Group 1', 'DNK3A'),
           League('Denmark', '2nd Division - Group 2', 'DNK3B'),
           League('Denmark', 'Kvindeliga', 'DNK1W'),
           League('Ecuador', 'Liga Pro', 'ECU1'),
           League('Ecuador', 'Liga Pro Serie B', 'ECU2'),
           League('Egypt', 'Premier League', 'EGY1'),
           League('England', 'Premier League', 'ENG1'),
           League('England', 'Championship', 'ENG2'),
           League('England', 'League One', 'ENG3'),
           League('England', 'League Two', 'ENG4'),
           League('England', 'National League', 'ENG5'),
           League('England', 'National League - North', 'ENG6A'),
           League('England', 'National League - South', 'ENG6B'),
           #League('England', 'Non League Premier - Isthmian', 'ENG7A'),
           #League('England', 'Non League Premier - Northern', 'ENG7B'),
           #League('England', 'Non League Premier - Southern South', 'ENG7C'),
           #League('England', 'Non League Premier - Southern Central', 'ENG7D'),
           League('England', 'Premier League 2 Division One', 'ENG7E'),
           League('England', 'Professional Development League', 'ENG7F'),
           League('England', 'FA WSL', 'ENG1W'),
           League('England', "Women''s Championship", 'ENG2W'),
           League('Spain', 'La Liga', 'ES1'),
           League('Spain', 'Segunda División', 'ES2'),
           League('Spain', 'Primera División RFEF - Group 1', 'ES3A'),
           League('Spain', 'Primera División RFEF - Group 2', 'ES3B'),
           League('Spain', 'Primera División Femenina', 'ES1W'),
           League('Estonia', 'Meistriliiga', 'EST1'),
           League('Ethiopia', 'Premier League', 'ETH1'),
           League('Finland', 'Veikkausliiga', 'FIN1'),
           League('Finland', 'Ykkönen', 'FIN2'),
           League('Finland', 'Kakkonen - Lohko A', 'FIN3A'),
           League('Finland', 'Kakkonen - Lohko B', 'FIN3B'),
           League('Finland', 'Kakkonen - Lohko C', 'FIN3C'),
           League('Finland', 'Kansallinen Liiga', 'FIN1W'),
           League('France', 'Ligue 1', 'FRA1'),
           League('France', 'Ligue 2', 'FRA2'),
           League('France', 'National 1', 'FRA3'),
           League('France', 'Feminine Division 1', 'FRA1W'),
           League('Georgia', 'Erovnuli Liga', 'GEO1'),
           League('Greece', 'Super League 1', 'GRC1'),
           League('Guatemala', 'Liga Nacional', 'GTM1'),
           League('Honduras', 'Liga Nacional', 'HND1'),
           League('Hungary', 'NB I', 'HUN1'),
           League('Hungary', 'NB II', 'HUN2'),
           League('India', 'Indian Super League', 'IND1'),
           League('Indonesia', 'Liga 1', 'IDN1'),
           League('Ireland', 'Premier Division', 'IRL1'),
           League('Ireland', 'First Division', 'IRL2'),
	   #League('Iran', 'Persian Gulf Pro League', 'IRN1'),
           League('Iceland', 'Úrvalsdeild', 'ISL1'),
           League('Iceland', '1. Deild', 'ISL2'),
           League('Iceland', 'Úrvalsdeild Women', 'ISL1W'),
           League('Israel', "Ligat Ha''al", 'ISR1'),
           League('Israel', 'Liga Leumit', 'ISR2'),
           League('Israel', 'Liga Alef', 'ISR3'),
           League('Italy', 'Serie A', 'ITA1'),
           League('Italy', 'Serie B', 'ITA2'),
           League('Italy', 'Serie C - Girone A', 'ITA3A'),
           League('Italy', 'Serie C - Girone B', 'ITA3B'),
           League('Italy', 'Serie C - Girone C', 'ITA3C'),
           League('Italy', 'Serie A Women', 'ITA1W'),
           League('Jamaica', 'Premier League', 'JAM1'),
           League('Japan', 'J1 League', 'JAP1'),
           League('Japan', 'J2 League', 'JAP2'),
           League('Japan', 'J3 League', 'JAP3'),
           League('Jordan', 'League', 'JOR1'),
           League('Kazakhstan', 'Premier League', 'KAZ1'),
	   #League('Kenya', 'FKF Premier League', 'KEN1'),
           League('South-Korea', 'K League 1', 'KOR1'),
           League('South-Korea', 'K League 2', 'KOR2'),
           League('South-Korea', 'K3 League', 'KOR3'),
           League('South-Korea', 'WK-League', 'KOR1W'),
           League('Kuwait', 'Premier League', 'KWT1'),
           League('Lithuania', 'A Lyga', 'LTU1'),
           League('Luxembourg', 'National Division', 'LUX1'),
           League('Latvia', 'Virsliga', 'LVA1'),
           League('Mexico', 'Liga MX', 'MEX1'),
           League('Mexico', 'Liga de Expansión MX', 'MEX2'),
           League('Mexico', 'Liga MX Femenil', 'MEX1W'),
           League('Morocco', 'Botola Pro', 'MOR1'),
           League('Macedonia', 'First League', 'MKD1'),
           League('Malta', 'Premier League', 'MLT1'),
	   #League('Montenegro', 'First League', 'MNE1'),
           League('Malaysia', 'Super League', 'MYS1'),
           League('Malaysia', 'Premier League', 'MYS2'),
           League('Nicaragua', 'Primera Division', 'NIC1'),
	   #League('Nigeria', 'NPFL', 'NIG1'),
           League('Northern-Ireland', 'Premiership', 'NIR1'),
           League('Netherlands', 'Eredivisie', 'NLD1'),
           League('Netherlands', 'Eerste Divisie', 'NLD2'),
           League('Netherlands', 'Eredivisie Women', 'NLD1W'),
           League('Norway', 'Eliteserien', 'NOR1'),
           League('Norway', '1. Division', 'NOR2'),
           League('Norway', '2. Division - Group 1', 'NOR3A'),
           League('Norway', '2. Division - Group 2', 'NOR3B'),
           League('Norway', 'Toppserien', 'NOR1W'),
	   #League('Oman', 'Professional League', 'OMN1'),
           League('Panama', 'Liga Panameña de Fútbol', 'PAN1'),
           League('Paraguay', 'Division Profesional - Apertura', 'PAR1A'),
           League('Paraguay', 'Division Profesional - Clausura', 'PAR1B'),
           League('Paraguay', 'Division Intermedia', 'PAR2'),
           League('Peru', 'Primera División', 'PER1'),
           League('Peru', 'Segunda División', 'PER2'),
           League('Poland', 'Ekstraklasa', 'POL1'),
           League('Poland', 'I Liga', 'POL2'),
           League('Portugal', 'Primeira Liga', 'PRT1'),
           League('Portugal', 'Segunda Liga', 'PRT2'),
           League('Portugal', 'Liga 3', 'PRT3'),
	   League('Portugal', 'Campeonato de Portugal Prio - Group A', 'PRT4A'),
	   League('Portugal', 'Campeonato de Portugal Prio - Group B', 'PRT4B'),
	   League('Portugal', 'Campeonato de Portugal Prio - Group C', 'PRT4C'),
	   League('Portugal', 'Campeonato de Portugal Prio - Group D', 'PRT4D'),
           League('Qatar', 'Stars League', 'QAT1'),
           League('Romania', 'Liga I', 'ROU1'),
           League('Romania', 'Liga II', 'ROU2'),
	   #League('Saudi-Arabia', 'Pro League', 'SAU1'),
	   #League('Saudi-Arabia', 'Division 1', 'SAU2'),
           League('Scotland', 'Premiership', 'SCO1'),
           League('Scotland', 'Championship', 'SCO2'),
           League('Scotland', 'League One', 'SCO3'),
           League('Scotland', 'League Two', 'SCO4'),
           League('Singapore', 'Premier League', 'SIN1'),
           League('Serbia', 'Super Liga', 'SRB1'),
           League('Serbia', 'Prva Liga', 'SRB2'),
           League('Slovakia', 'Super Liga', 'SVK1'),
           League('Slovakia', '2. liga', 'SVK2'),
           League('Slovenia', '1. SNL', 'SVN1'),
           League('Slovenia', '2. SNL', 'SVN2'),
           League('Sweden', 'Allsvenskan', 'SWE1'),
           League('Sweden', 'Superettan', 'SWE2'),
           League('Sweden', 'Ettan - Norra', 'SWE3A'),
           League('Sweden', 'Ettan - Södra', 'SWE3B'),
           League('Sweden', 'Damallsvenskan', 'SWE1W'),
           League('Thailand', 'Thai League 1', 'THA1'),
           League('Thailand', 'Thai League 2', 'THA2'),
           League('Tunisia', 'Ligue 1', 'TUN1'),
           League('Turkey', 'Süper Lig', 'TUR1'),
           League('Turkey', '1. Lig', 'TUR2'),
	   #League('Turkey', '2. Lig', 'TUR3'),
	   #League('United-Arab-Emirates', 'Pro League', 'UAE1'),
	   #League('Uganda', 'Premier League', 'UGA1'),
           League('Ukraine', 'Premier League', 'UKR1'),
           League('Uruguay', 'Primera División - Apertura', 'URU1'),
           League('Uruguay', 'Primera División - Clausura', 'URU2'),
           League('USA', 'Major League Soccer', 'USA1'),
           League('USA', 'USL Championship', 'USA2'),
	   #League('USA', 'USL League One', 'USA3'),
           League('USA', 'NWSL Women', 'USA1W'),
           League('Venezuela', 'Primera División', 'VEN1'),
           League('Vietnam', 'V.League 1', 'VIE1'),
           League('Wales', 'Premier League', 'WAL1'),
           League('South-Africa', 'Premier Soccer League', 'ZAF1')]

league_register = {league.code: league for league in leagues}
