from collections import OrderedDict
from lib import messages


def prettify(country_name: str) -> str:
    sep = '-'
    if sep in country_name:
        lexemes = country_name.split(sep)
        return ' '.join(lex.capitalize() for lex in lexemes)
    else:
        return country_name


class League:
    __slots__ = ['country', 'name']

    def __init__(self, country: str, name: str):
        self.country = country
        self.name = name

    def __str__(self):
        return '{} {}'.format(prettify(self.country), self.name)


country_register = [
    'Albania',
    'Algeria',
    'Argentina',
    'Australia',
    'Austria',
    'Azerbaidjan',
    'Bahrain',
    'Belarus',
    'Belgium',
    'Bolivia',
    'Bosnia',
    'Brazil',
    'Bulgaria',
    'Canada',
    'Chile',
    'China',
    'Colombia',
    'Costa-Rica',
    'Croatia',
    'Cyprus',
    'Czech-Republic',
    'Denmark',
    'Ecuador',
    'Egypt',
    'England',
    'Estonia',
    'Finland',
    'France',
    'Georgia',
    'Germany',
    'Greece',
    'Guatemala',
    'Honduras',
    'Hungary',
    'Iceland',
    'India',
    'Iran',
    'Ireland',
    'Israel',
    'Italy',
    'Japan',
    'Jordan',
    'Kazakhstan',
    'Kenya',
    'Kosovo',
    'Kuwait',
    'Latvia',
    'Liechtenstein',
    'Lithuania',
    'Luxembourg',
    'Malaysia',
    'Malta',
    'Mexico',
    'Montenegro',
    'Morocco',
    'Netherlands',
    'New-Zealand',
    'Nicaragua',
    'Nigeria',
    'Northern-Ireland',
    'Norway',
    'Oman',
    'Panama',
    'Paraguay',
    'Peru',
    'Poland',
    'Portugal',
    'Qatar',
    'Romania',
    'Russia',
    'Saudi-Arabia',
    'Scotland',
    'Serbia',
    'Slovakia',
    'Slovenia',
    'South-Africa',
    'South-Korea',
    'Spain',
    'Sweden',
    'Switzerland',
    'Thailand',
    'Tunisia',
    'Turkey',
    'Ukraine',
    'United-Arab-Emirates',
    'USA',
    'Uganda',
    'Uzbekistan',
    'Venezuela',
    'Vietnam',
    'Wales']

league_register = OrderedDict({
    'ALB1': League('Albania', 'Superliga'),
    'ALG1': League('Algeria', 'Ligue 1'),
    'ARG1': League('Argentina', 'Primera Division'),
    'ARG2A': League('Argentina', 'Primera B Nacional'),
    'ARG2B': League('Argentina', 'Primera B Metropolitana'),
    'ARG3': League('Argentina', 'Primera C'),
    'AUS1': League('Australia', 'A-League'),
    'AUS1W': League('Australia', 'W-League'),
    'AUT1': League('Austria', 'Tipp3 Bundesliga'),
    'AUT2': League('Austria', 'Erste Liga'),
    'AZE1': League('Azerbaidjan', 'Premyer Liqa'),
    'BEL1': League('Belgium', 'Jupiler Pro League'),
    'BHR1': League('Bahrain', 'Premier League'),
    'BRA1': League('Brazil', 'Serie A'),
    'BRA2': League('Brazil', 'Serie B'),
    'BRA3': League('Brazil', 'Serie C'),
    'BGR1': League('Bulgaria', 'A PFG'),
    'BGR2': League('Bulgaria', 'B PFG'),
    'BOL1': League('Bolivia', 'Primera División'),
    'BIH1': League('Bosnia', 'Premijer Liga'),
    'BLR1': League('Belarus', 'Vysshaya Liga'),
    'BLR2': League('Belarus', '1. Division'),
    'CHE1': League('Switzerland', 'Super League'),
    'CHE2': League('Switzerland', 'Challenge League'),
    'CHN1': League('China', 'Super League'),
    'CHN2': League('China', 'League One'),
    'CHL1': League('Chile', 'Primera Division'),
    'CHL2': League('Chile', 'Primera B'),
    'COL1': League('Colombia', 'Primera A'),
    'COL2': League('Colombia', 'Primera B'),
    'CRI1': League('Costa-Rica', 'Primera Division'),
    'CRI2': League('Costa-Rica', 'Liga De Ascenso'),
    'HRV1': League('Croatia', 'Prva HNL'),
    'HRV2': League('Croatia', 'Druga HNL'),
    'CYP1': League('Cyprus', '1. Division'),
    'CZE1': League('Czech-Republic', 'Czech Liga'),
    'CZE2': League('Czech-Republic', 'FNL'),
    'DEU1': League('Germany', 'Bundesliga 1'),
    'DEU2': League('Germany', 'Bundesliga 2'),
    'DEU3': League('Germany', 'Liga 3'),
    'DEU1W': League('Germany', 'Women Bundesliga'),
    'DNK1': League('Denmark', 'Superligaen'),
    'DNK2': League('Denmark', 'Viasat Divisionen'),
    'ECU1': League('Ecuador', 'Serie A'),
    'ECU2': League('Ecuador', 'Serie B'),
    'EGY1': League('Egypt', 'Premier League'),
    'ENG1': League('England', 'Premier League'),
    'ENG2': League('England', 'Championship'),
    'ENG3': League('England', 'League One'),
    'ENG4': League('England', 'League Two'),
    'ENG5': League('England', 'National League'),
    'ENG6A': League('England', 'National League - North'),
    'ENG6B': League('England', 'National League - South'),
    'ENG1W': League('England', 'FA WSL'),
    'ESP1': League('Spain', 'Primera Division'),
    'ESP2': League('Spain', 'Segunda Division'),
    'ESP3A': League('Spain', 'Segunda Division - Group 1'),
    'ESP3B': League('Spain', 'Segunda Division - Group 2'),
    'ESP3C': League('Spain', 'Segunda Division - Group 3'),
    'ESP3D': League('Spain', 'Segunda Division - Group 4'),
    'ESP3E': League('Spain', 'Segunda Division - Group 5'),
    'ESP1W': League('Spain', 'Primera Division Women'),
    'EST1': League('Estonia', 'Meistriliiga'),
    'EST2': League('Estonia', 'Esiliiga A'),
    'FIN1': League('Finland', 'Veikkausliiga'),
    'FIN2': League('Finland', 'Ykkonen'),
    'FIN1W': League('Finland', 'Naisten Liiga'),
    'FRA1': League('France', 'Ligue 1'),
    'FRA2': League('France', 'Ligue 2'),
    'FRA3': League('France', 'National'),
    'FRA1W': League('France', 'Feminine Division 1'),
    'GEO1': League('Georgia', 'Erovnuli Liga'),
    'GRC1': League('Greece', 'Super League'),
    'GTM1': League('Guatemala', 'Primera Division'),
    'HND1': League('Honduras', 'Liga Nacional de Fútbol'),
    'HUN1': League('Hungary', 'NB I'),
    'HUN2': League('Hungary', 'NB II'),
    'IND1': League('India', 'Indian Super League'),
    'IND2': League('India', 'I-League'),
    'IRL1': League('Ireland', 'Premier Division'),
    'IRN1': League('Iran', 'Persian Gulf Cup'),
    'IRN2': League('Iran', 'Azadegan League'),
    'ISL1': League('Iceland', 'Premier'),
    'ISL2': League('Iceland', 'Division 1'),
    'ISL3': League('Iceland', 'Division 2'),
    'ISL1W': League('Iceland', 'Úrvalsdeild Women'),
    'ISR1': League('Israel', "Ligat ha''Al"),
    'ISR2': League('Israel', 'Liga Leumit'),
    'ITA1': League('Italy', 'Serie A'),
    'ITA2': League('Italy', 'Serie B'),
    'ITA3': League('Italy', 'Serie C'),
    'ITA1W': League('Italy', 'Serie A Women'),
    'JAP1': League('Japan', 'J. League Div.1'),
    'JAP2': League('Japan', 'J. League Div.2'),
    'JAP3': League('Japan', 'J. League Div.3'),
    'JOR1': League('Jordan', 'Division 1'),
    'KAZ1': League('Kazakhstan', 'Premier League'),
    'KEN1': League('Kenya', 'Premier League'),
    'KOR1': League('South-Korea', 'K-League Classic'),
    'KOR2': League('South-Korea', 'K-League Challenge'),
    'KWT1': League('Kuwait', 'Premier League'),
    'LTU1': League('Lithuania', 'A Lyga'),
    'LTU2': League('Lithuania', '1 Lyga'),
    'LUX1': League('Luxembourg', 'National Division'),
    'LVA1': League('Latvia', 'Virsliga'),
    'LVA2': League('Latvia', '1. Liga'),
    'MEX1': League('Mexico', 'Liga MX'),
    'MEX2': League('Mexico', 'Ascenso MX'),
    'MOR1': League('Morocco', 'Botola Pro'),
    'MLT1': League('Malta', 'Premier League'),
    'MLT2': League('Malta', 'First Division'),
    'MNE1': League('Montenegro', 'First League'),
    'MNE2': League('Montenegro', 'Second League'),
    'MYS1': League('Malaysia', 'Super League'),
    'MYS2': League('Malaysia', 'Premier League'),
    'NIR1': League('Northern-Ireland', 'Premiership'),
    'NIR2': League('Northern-Ireland', 'Championship'),
    'NLD1': League('Netherlands', 'Eredivisie'),
    'NLD2': League('Netherlands', 'Eerste Divisie'),
    'NLD1W': League('Netherlands', 'Eredivisie Women'),
    'NIC1': League('Nicaragua', 'Primera Division'),
    'NIG1': League('Nigeria', 'NPFL'),
    'NOR1': League('Norway', 'Eliteserien'),
    'NOR2': League('Norway', 'OBOS-ligaen'),
    'OMN1': League('Oman', 'Professional League'),
    'PAN1': League('Panama', 'Liga Panameña de Fútbol'),
    'PAR1': League('Paraguay', 'Primera Division - Apertura'),
    'PAR2': League('Paraguay', 'Primera Division - Clausura'),
    'PER1': League('Peru', 'Primera Division'),
    'POL1': League('Poland', 'Ekstraklasa'),
    'POL2': League('Poland', 'I Liga'),
    'PRT1': League('Portugal', 'Primeira Liga'),
    'PRT2': League('Portugal', 'Liga de Honra'),
    'QAT1': League('Qatar', 'Stars League'),
    'ROU1': League('Romania', 'Liga I'),
    'ROU2': League('Romania', 'Liga II'),
    'RUS1': League('Russia', 'Premier League'),
    'RUS2': League('Russia', 'Football National League'),
    'SAU1': League('Saudi-Arabia', 'Pro League'),
    'SAU2': League('Saudi-Arabia', 'Division 1'),
    'SCO1': League('Scotland', 'Premiership'),
    'SCO2': League('Scotland', 'Championship'),
    'SCO3': League('Scotland', 'League One'),
    'SCO4': League('Scotland', 'League Two'),
    'SRB1': League('Serbia', 'Super Liga'),
    'SRB2': League('Serbia', 'Prva Liga'),
    'SVK1': League('Slovakia', 'Super Liga'),
    'SVK2': League('Slovakia', '2. liga'),
    'SVN1': League('Slovenia', '1. SNL'),
    'SVN2': League('Slovenia', '2. SNL'),
    'SWE1': League('Sweden', 'Allsvenskan'),
    'SWE2': League('Sweden', 'Superettan'),
    'SWE3A': League('Sweden', 'Ettan - Norra'),
    'SWE3B': League('Sweden', 'Ettan - Södra'),
    'SWE1W': League('Sweden', 'Damallsvenskan'),
    'THA1': League('Thailand', 'Thai Premier League'),
    'THA2': League('Thailand', 'Thai League 2'),
    'TUN1': League('Tunisia', 'Ligue Professionnelle 1'),
    'TUR1': League('Turkey', 'Super Lig'),
    'TUR2': League('Turkey', 'TFF 1. Lig'),
    'TUR3': League('Turkey', 'TFF 2. Lig'),
    'UAE1': League('United-Arab-Emirates', 'Arabian Gulf League'),
    'UAE2': League('United-Arab-Emirates', 'Division 1'),
    'UGA1': League('Uganda', 'Premier League'),
    'UKR1': League('Ukraine', 'Premier League'),
    'UKR2': League('Ukraine', 'Persha League'),
    'USA1': League('USA', 'Major League Soccer'),
    'UZB1': League('Uzbekistan', 'Super League'),
    'VEN1': League('Venezuela', 'Primera Division'),
    'VEN2': League('Venezuela', 'Segunda Division'),
    'VIE1': League('Vietnam', 'V.League 1'),
    'WAL1': League('Wales', 'Premier'),
    'XXK1': League('Kosovo', 'Superliga'),
    'ZAF1': League('South-Africa', 'Premier Soccer League'),
    'ZAF2': League('South-Africa', '1st Division')
})

for league in league_register.values():
    if league.country not in country_register:
        messages.error_message("Unrecognised country '{}' for league".format(league.country))


def get_league_code(league: League) -> str:
    for key, candidate in league_register.items():
        if candidate.name == league.name and candidate.country == league.country:
            return key
