class JSON_Keys:
    bench = 'bench'
    birthDate = 'birthDate'
    competitionId = 'competitionId'
    dateutc = 'dateutc'
    eventId = 'eventId'
    eventSec = 'eventSec'
    firstName = 'firstName'
    foot = 'foot'
    formation = 'formation'
    goals = 'goals'
    home_score = 'home_score'
    id_ = 'id'
    lastName = 'lastName'
    lineup = 'lineup'
    matchId = 'matchId'
    matchPeriod = 'matchPeriod'
    minute = 'minute'
    name = 'name'
    ownGoals = 'ownGoals'
    playerId = 'playerId'
    playerIn = 'playerIn'
    playerOut = 'playerOut'
    positions = 'positions'
    redCards = 'redCards'
    role = 'role'
    score = 'score'
    scoreHT = 'scoreHT'
    season = 'season'
    seasonId = 'seasonId'
    shortName = 'shortName'
    side = 'side'
    subEventId = 'subEventId'
    substitutions = 'substitutions'
    tags = 'tags'
    teamsData = 'teamsData'
    teamId = 'teamId'
    team_name = 'team_name'
    timestamp = 'timestamp'
    wyId = 'wyId'
    x = 'x'
    y = 'y'
    yellowCards = 'yellowCards'


def decode_json_string(value: str):
    return value.encode('utf-8').decode('unicode-escape').strip()
